todo1 = Todo.create(title: "make money", body: "yessss", done: true)
todo2 = Todo.create(title: "get wrecked", body: "hi", done: true)
todo3 = Todo.create(title: "jump", body: "high", done: false)
todo4 = Todo.create(title: "fly", body: "like an eagle", done: false)
todo5 = Todo.create(title: "yolo", body: "for narnia", done: true)
